server:
  port: 9999
  servlet:
    session:
      timeout: 30
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  session:
    store-type: redis
