#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: gulimall-third-party
#server:
#  port: 30000
#
#gulimall:
#  sms:
#    sms-access-key-id: xxx
#    sms-access-key-secret: xxxx
#    sms-endpoint: dysmsapi.aliyuncs.com
#    sms-template-code: xxx
#    sms-sign-name: xxx
